### ISSUE TITLE
error: Invalid serialized PackageId for key `package.dependencies` 

### ISSUE THREAD

**Issue by brocaar** [cardoe/cargo-bitbake#13]
I'm getting the following error:

```
error: failed to parse lock file at: Cargo.lock

Caused by:
  invalid serialized PackageId for key `package.dependencies`
```

Probably this is caused by https://github.com/rust-lang/cargo/pull/7579 (I found this reference in https://github.com/sfackler/cargo-tree/issues/80, where the same issue was reported).

**Comment by dellgreen** [comment]
I'm also seeing the same issue
