### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [cardoe/cargo-bitbake#2]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

**Comment by cardoe** [comment]
I'd honestly love to. I've stopped using it and switched to Serde for most of my projects already. The reason for this is that I use Cargo to parse the args and the latest Cargo version, 0.17 requires struct that defines the options to derive `RustcDecodable`.

**Comment by cardoe** [comment]
Here's the current error when I attempt to use Serde.
```
let result = cargo::call_main_without_stdin(real_main, &config, USAGE, &args, false);
    |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `rustc_serialize::serialize::Decodable` is not implemented for `Options`
```

**Comment by dtolnay** [comment]
Cool, I filed https://github.com/rust-lang/cargo/issues/3944 to track this on Cargo's end.

**Comment by cardoe** [comment]
Thanks. I might drop using that entry point and switch to clap to parse the args and then I can drop rustc-serialize.
