### ISSUE TITLE
Feature request: Support closed source licenses

### ISSUE THREAD

**Issue by hmvp** [cardoe/cargo-bitbake#4]
Cargo bitbake won't generate a recipe when there is no license info in Cargo.toml
However for internal projects there might not be a license. 
```
LICENSE = "CLOSED"
```
in a recipe is a valid way to signal yocto that there is no valid license. However if I use that I still get 
```
# FIXME: update generateme with the real MD5 of the license file
LIC_FILES_CHKSUM=" \
file://CLOSED;md5=generateme \
"
```
in the generated file.

It would be nice if that could be left out

**Comment by cardoe** [comment]
Thank you for the ticket. For reference the documentation behind this is available at http://www.yoctoproject.org/docs/2.3.2/mega-manual/mega-manual.html#sdk-license-detection

**Comment by cardoe** [comment]
Please see https://github.com/cardoe/cargo-bitbake/tree/license-closed and let me know if you think that'll work. You can test it by cloning the repo and checking out that branch and running `cargo install -f` in the top level directory.

**Comment by hmvp** [comment]
This seems to work as expected. It still leaves a superfluous 
```
# FIXME: update generateme with the real MD5 of the license file
LIC_FILES_CHKSUM=" \
"
```
But that does not leave a warning during the build.

Thanks!

**Comment by cardoe** [comment]
As far as removing it out entirely it would be a bunch more work. I would certainly accept a patch to clean that up.
